"""
Soul.md API — read/write Hermes identity files (USER.md + MEMORY.md).
Mirrors the "soul.md" template from Jack Roberts' Hermes OS.
"""
import os
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/api/soul", tags=["soul"])

MEMORIES_DIR = os.path.expanduser("~/.hermes/memories")
USER_PATH = os.path.join(MEMORIES_DIR, "USER.md")
MEMORY_PATH = os.path.join(MEMORIES_DIR, "MEMORY.md")

# Structured sections per Jack's soul.md template
SOUL_SECTIONS = {
    "identity": {
        "title": "Identity",
        "fields": ["name", "role", "location", "languages", "bio"],
        "description": "Who you are — name, role, context Hermes needs to know"
    },
    "mission": {
        "title": "Mission & Goals",
        "fields": ["yearly_goal", "quarterly_goals", "north_star"],
        "description": "What you're working toward. Be specific with numbers."
    },
    "business": {
        "title": "Business & Revenue",
        "fields": ["business_model", "monthly_revenue", "runway_months", "key_metrics"],
        "description": "Your business context — revenue, runway, metrics Hermes should track"
    },
    "voice": {
        "title": "Voice & Communication",
        "fields": ["tone", "language_preference", "response_style", "pet_peeves"],
        "description": "How Hermes should communicate with you"
    },
    "tools": {
        "title": "Tools & Stack",
        "fields": ["preferred_models", "active_platforms", "key_integrations"],
        "description": "Your tech stack and preferred tools"
    }
}


def _read_file(path: str) -> str:
    """Read a file, return empty string if missing."""
    try:
        return Path(path).read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Read error: {e}")


def _write_file(path: str, content: str):
    """Write a file atomically."""
    import tempfile
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # Write to temp file, then rename
        tmp_path = path + ".tmp"
        with open(tmp_path, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Write error: {e}")


def _parse_soul_sections(content: str) -> dict:
    """
    Parse a soul.md file into structured sections.
    Sections are delimited by ## headings.
    """
    sections = {}
    current_section = None
    current_content = []
    
    for line in content.split("\n"):
        if line.startswith("## "):
            if current_section:
                sections[current_section] = "\n".join(current_content).strip()
            current_section = line[3:].strip().lower().replace(" ", "_")
            current_content = []
        else:
            current_content.append(line)
    
    if current_section:
        sections[current_section] = "\n".join(current_content).strip()
    
    return sections


def _build_soul_document(sections: dict) -> str:
    """Build a soul.md document from structured sections."""
    lines = ["# Soul.md — Hermes Identity", ""]
    lines.append(f"*Auto-generated by Hermes OS. Edit via the Soul Editor.*")
    lines.append("")
    
    section_order = ["identity", "mission", "business", "voice", "tools"]
    for key in section_order:
        if key in sections:
            title = key.replace("_", " ").title()
            lines.append(f"## {title}")
            lines.append("")
            lines.append(sections[key].strip())
            lines.append("")
    
    return "\n".join(lines)


@router.get("/user")
async def get_user_soul():
    """Get USER.md as structured sections."""
    content = _read_file(USER_PATH)
    sections = _parse_soul_sections(content)
    
    return {
        "raw": content,
        "sections": sections,
        "stats": {
            "char_count": len(content),
            "line_count": len(content.split("\n")),
            "file": USER_PATH
        },
        "template": SOUL_SECTIONS
    }


@router.get("/memory")
async def get_memory():
    """Get MEMORY.md content."""
    content = _read_file(MEMORY_PATH)
    return {
        "raw": content,
        "stats": {
            "char_count": len(content),
            "line_count": len(content.split("\n")),
            "file": MEMORY_PATH
        }
    }


@router.put("/user")
async def update_user_soul(data: dict):
    """
    Update USER.md with structured sections.
    Body: {"sections": {"identity": "...", "mission": "...", ...}}
    """
    sections = data.get("sections", {})
    content = _build_soul_document(sections)
    _write_file(USER_PATH, content)
    
    return {
        "status": "ok",
        "saved": True,
        "stats": {"char_count": len(content), "line_count": len(content.split("\n"))}
    }


@router.put("/user/raw")
async def update_user_soul_raw(data: dict):
    """
    Update USER.md with raw markdown content.
    Body: {"content": "full markdown string"}
    """
    content = data.get("content", "")
    _write_file(USER_PATH, content)
    
    return {
        "status": "ok",
        "saved": True,
        "stats": {"char_count": len(content), "line_count": len(content.split("\n"))}
    }


@router.put("/memory")
async def update_memory(data: dict):
    """
    Update MEMORY.md with raw markdown content.
    Body: {"content": "full markdown string"}
    """
    content = data.get("content", "")
    _write_file(MEMORY_PATH, content)
    
    return {
        "status": "ok",
        "saved": True,
        "stats": {"char_count": len(content), "line_count": len(content.split("\n"))}
    }